build_ubuntu:
    stage: build
    image: ubuntu
    tags: 
        - ubuntu
    script:
        - apt-get update && apt-get upgrade -y
        - DEBIAN_FRONTEND=noninteractive nice apt-get install -y build-essential cmake libopenvdb-dev
        - git submodule update --init --recursive
        - cmake -S . -B build -DVOLDATA_BUILD_TOOLS=ON -DCMAKE_BUILD_TYPE=Release -Wno-dev && nice cmake --build build --parallel
